# Generated by Django 4.1.1 on 2022-09-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='playback_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='playback_time_instant',
            field=models.FloatField(default=0),
        ),
    ]
