# Generated by Django 4.1.1 on 2022-09-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_data', '0002_event_playback_id_event_playback_time_instant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.TextField(default=''),
        ),
    ]
